name: Lint Code Base

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]


jobs:
  backend-lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Run lint
        uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_ISORT: true
          VALIDATE_TSX: true
          VALIDATE_TYPESCRIPT_STANDARD: true
          LINTER_RULES_PATH: /
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
          PYTHON_ISORT_CONFIG_FILE: pyproject.toml
          JAVASCRIPT_DEFAULT_STYLE: "prettier"
